# Generated by Django 6.1.1 on 2026-09-21 03:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BitacoraAccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=255, verbose_name='Acción realizada')),
                ('detalles', models.TextField(blank=True, null=True, verbose_name='Detalles de la acción')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Admin')),
            ],
            options={
                'verbose_name': 'Bitácora de Acción',
                'verbose_name_plural': 'Bitácora de Acciones',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
